#!/bin/bash

./add_material.py \
--title "THIS is a TEST" \
--src1 https://drive.internxt.com/sh/file/94f389e5-233f-4ef8-bf4a-5ed6ebfa1d75/fb91f7f91687e8bc057e261c3d3ab8b370db0d5e27b751685dc91ce0e871a855 \
--src1_title "View/Download 'THIS is a TEST' (15 pages)" \

