#!/bin/bash
gh auth login --with-token <  ~/.ssh/gh_token
gh repo delete  tholonia.github.io --yes
gh repo create  tholonia.github.io --public 

rm -rf .git
rm .gitattributes
rm -rf _site/*

GIT_TRACE=1
git init
git branch -M main
git remote add origin git@github.com:tholonia/tholonia.github.io.git

git lfs install
# auto track
find -type f -name "THOLONIA_THE_BOOK*"|awk '{print "git lfs track "$1}' |sh
find -type f -name "THOLONIA_THE_BOOK*"|awk '{print "git add -f  "$1}' |sh

# all books are LFS
git lfs track "_material/assets/book*.zip"
git add -f _material/assets/book*.zip
#git lfs track "_material/assets/book*.pdf"
#git add "_material/assets/book*.pdf"
git add .gitattributes
git lfs status ; git lfs ls-files # check that they are committed
git commit -m "Tracking and adding LFS artifacts"
git push origin main

# check for any files over githuib limit
# find -size +100M

# now add the rest of the content
git add .
git commit -m "first commit after LFS"
git push origin main

